[package]
name = "calibre-cranelift-jit"
version = "0.1.0"
edition = "2024"

[dependencies]
cranelift = "0.123.2"
cranelift-module = "0.123.2"
cranelift-jit = "0.123.2"
cranelift-native ="0.123.2"
calibre-parser = {workspace = true}
rand = "0.9.2"
