[package]
name = "calibre-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
rand = "0.9.1"
rustyline = "16.0.0"
thiserror = "2.0.12"
rust-sitter = "0.4.5"

[build-dependencies]
rust-sitter-tool = "0.4.5"
