[package]
name = "calibre"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
name = "calibre"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "calibre"
path = "src/main.rs"
required-features = ["cli"]

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory",
    "-C", "link-arg=--shared-memory",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--max-memory=1073741824",
    "-C", "link-arg=--export=__stack_pointer",
    "-C", "link-arg=--export=__tls_base",
    "-C", "link-arg=--export=__tls_size",
    "-C", "link-arg=--export=__tls_align",
    "-C", "link-arg=--export=__wasm_init_tls",
]


[features]
default = ["cli"]
cli = ["clap", "rustyline", "glob", "smol", "tracing-flame", "tracing-appender", "tracing-subscriber", "calibre-vm/native", "calibre-parser/native"]
wasm = ["wasm-bindgen", "js-sys", "getrandom/js", "calibre-parser/wasm", "calibre-mir/wasm", "calibre-vm/wasm"]
python = ["pyo3"]
ffi = ["cbindgen"]

[dependencies]
clap = { workspace = true, optional = true }
calibre-parser = {workspace = true}
calibre-diagnostics = {workspace = true}
calibre-mir = { workspace = true }
calibre-lir = { workspace = true }
calibre-vm = { workspace = true }
calibre-std = { workspace = true }
serde = { workspace = true }
rustyline = {workspace = true, optional = true }
thiserror = {workspace = true }
rustc-hash = { workspace = true }
tracing = { workspace = true }
wasm_thread = { workspace = true }
wasm_sync = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
tracing-flame = { workspace = true, optional = true }
tracing-appender = { workspace = true, optional = true }
smol = { workspace = true, optional = true }
derive_builder = { workspace = true }

bincode = "1"
serde_json = "1"
blake3 = "1.6.1"
toml = "1.0.1"
glob = {version = "0.3.1", optional = true}
ustr = { workspace = true }

wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
getrandom = { version = "0.2", optional = true }
pyo3 = { version = "0.18", optional = true, features = ["extension-module"] }

[build-dependencies]
cbindgen = {version = "0.28", optional = true}
