[package]
name = "calibre"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
calibre-parser = {workspace = true}
calibre-diagnostics = {workspace = true}
calibre-mir = { workspace = true }
calibre-lir = { workspace = true }
calibre-vm = { workspace = true }
calibre-std = { workspace = true }
serde = { workspace = true }
rustyline = {workspace = true }
thiserror = {workspace = true }
rustc-hash = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-flame = { workspace = true }
tracing-appender = { workspace = true }
smol = { workspace = true }

clap = { version = "4.5.40", features = ["derive"] }
bincode = "1"
blake3 = "1.6.1"
toml = "1.0.1"
glob = "0.3.1"
