[package]
name = "calibre-vm"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
tracing = { workspace = true }
calibre-lir = { workspace = true }
calibre-parser = { workspace = true }
fastrand = { workspace = true }
thiserror = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
indextree = { workspace = true }
wasm_lite_std = { workspace = true}
dumpster = "2.0.0"
libloading = {version = "0.9", optional = true }
libffi = {version = "4", optional = true }
regex = "1.10.6"
sha2 = "0.10.8"
blake3 = "1.5.4"
hex = "0.4.3"

ureq = {version = "3", optional = true }
socket2 = {version = "0.6", optional = true }
errno = { version = "0.3.14", optional = true }
astro-float = "=0.9.6"

[features]
native = ["errno", "libffi", "libloading", "ureq", "socket2"]
